services:
  pihole:
    # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # HTTP Port for admin portal
      - "3000:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "4431:443/tcp"
    environment:
      TZ: "Europe/Copenhagen"
      FTLCONF_webserver_api_password: ${PI_HOLE_PASSWORD}
      FTLCONF_dns_listeningMode: "all"
    volumes:
      - "./data/etc-pihole:/etc/pihole"
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
      - SYS_TIME # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_NICE # Optional, if Pi-hole should get some more processing time
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          cpus: "0.2"
      update_config:
        order: start-first

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/data-portainer:/data

  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_DOMAIN}
      HOMEPAGE_VAR_PI_HOLE_PASSWORD: ${PI_HOLE_PASSWORD}
      HOMEPAGE_VAR_PORTAINER_API_KEY: ${PORTAINER_API_KEY}
    volumes:
      - ./homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest-alpine
    volumes:
      - "./data/data-vaultwarden:/data/"
    environment:
      DOMAIN: https://${VAULTWARDEN_SUBDOMAIN}.${DOMAIN}
      SIGNUPS_ALLOWED: true
    restart: unless-stopped

  caddy:
    image: serfriz/caddy-porkbun-dockerproxy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy-config:/config
      - ./data/caddy-data:/data
      - /var/run/docker.sock:/var/run/docker.sock # Proxy the docker socket so it has access to networking
    environment:
      CADDY_DOCKER_CADDYFILE_PATH: /etc/caddy/Caddyfile

      DOMAIN: ${DOMAIN}
      VAULTWARDEN_SUBDOMAIN: ${VAULTWARDEN_SUBDOMAIN}
      PORTAINER_SUBDOMAIN: ${PORTAINER_SUBDOMAIN}
      HOMEPAGE_DOMAIN: ${HOMEPAGE_DOMAIN}

      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      PORKBUN_API_SECRET_KEY: ${PORKBUN_API_SECRET_KEY}
